destination: ./build

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

collections:
  projects:
    output: true
  extras:
    output: true
  blog:
    output: true
  gallery:
    output: true
  docs:
    output: true
    permalink: /docs/:path/
